apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: 'https://github.com/grafana/helm-charts.git'
      targetRevision: main
      path: charts/grafana
      helm:
        valueFiles:
          - $myrepo/internal-psi-monitoring/applications/grafana/values.yaml
    - repoURL: 'https://github.com/oyegokeodev/oye-gitops.git'
      targetRevision: HEAD
      ref: myrepo
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  ignoreDifferences:
    - group: ""
      kind: Secret
      name: grafana
      namespace: monitoring
      jsonPointers:
        - /data/admin-password
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
